### ISSUE TITLE
Native DLL doesn't load on Windows

### ISSUE THREAD

**Issue by marklam** [Apollo3zehn/Blosc2.PInvoke#1]
It looks like it attempts to load "blosc2.dll" but the file in the runtime folder is "libblosc2.dll"

**Comment by Apollo3zehn** [comment]
Is version [2.7.2](https://www.nuget.org/packages/Blosc2.PInvoke/2.7.2) working better for you?

**Comment by marklam** [comment]
Yes that seems to work (ie the filter starts OK)
